### ISSUE TITLE
TableEx, Options for Styles

### ISSUE THREAD

**Issue by HarryLeboeuf** [deldersveld/PowerBI-ThemeTemplates#26]
In PBI Desktop we can choose different styles for a table.
Do you have any idea what are the enumerator values in json for these styles.

**Comment by 7samat** [comment]
The enum list for table style is:

'AlternatingRows'
'BoldHeader'
'Minimal'
'Condensed'
'ContrastAlternatingRows'
'Sparse'
'BoldHeaderFlashyRows'
'None'
'FlashyRows'
