### ISSUE TITLE
Shadow definitions

### ISSUE THREAD

**Issue by dipanos** [deldersveld/PowerBI-ThemeTemplates#30]
Does anyone know how to set "Shadow position" to "Inside" within a json script? No matter what I declare it always turns to "Outside"

**Comment by 7samat** [comment]
I am using the below and it seems to work fine:

`"dropShadow": [{ "position": "Inner" }]`

**Comment by dipanos** [comment]
Yes, just tested my self and it works, thanks!

**Comment by 7samat** [comment]
Also, do remember that this is case sensitive so `inner` would not work. `Outer` is also the default so a typo here would trigger it to be applied.

**Comment by dipanos** [comment]
Do you by any chance have you manage to declare "Display Units" value in any visual?

**Comment by 7samat** [comment]
> Do you by any chance have you manage to declare "Display Units" value in any visual?

This is an example (millions) that seems to work on my end:

`"labels": [	{ 	"labelDisplayUnits": 1000000	}	]`
